trigger:
  - master
  
pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
  functionAppName: 'java-FunctionApp'

steps:
- task: Cache@2
  inputs:
    key: 'maven | "$(Agent.OS)" | **/pom.xml'
    restoreKeys: |
      maven | "$(Agent.OS)"
      maven
    path: $(MAVEN_CACHE_FOLDER)
  displayName: Cache Maven local repo
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m $(MAVEN_OPTS)'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: CopyFiles@2
  inputs:
    SourceFolder: $(system.defaultworkingdirectory)/target/azure-functions/$(functionAppName)/
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'Visual Studio Professional Subscription(e28dc30c-8494-4d6d-9407-2202582cb056)'
    appType: 'functionApp'
    appName: 'java-func-app'
    package: '$(build.artifactstagingdirectory)'
    appSettings: '-ConnectionString "host:qadb;port:1234;db:qa;password:qwerty"'
    deploymentMethod: 'auto'
- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'Visual Studio Professional Subscription(e28dc30c-8494-4d6d-9407-2202582cb056)'
    appType: 'functionApp'
    appName: 'java-func-app-prod'
    package: '$(build.artifactstagingdirectory)'
    appSettings: '$(PRODAPPSETTINGS)'
    deploymentMethod: 'auto'